-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."CONTAINER"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    capacity character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL,
    CONSTRAINT "CONTAINER_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CONTAINER_PRIORITY"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    priority integer NOT NULL,
    max_capacity double precision NOT NULL,
    max_weight double precision NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    container_type_id bigint,
    CONSTRAINT "CONTAINER_PRIORITY_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CONTAINER_THRESHOLD"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    "CONTAINER_TYPE" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    min_capacity double precision NOT NULL,
    max_capacity double precision NOT NULL,
    status boolean NOT NULL,
    container_id bigint,
    port_of_loading_id bigint,
    CONSTRAINT "CONTAINER_THRESHOLD_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CUSTOMER"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    contact_person character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    country character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tax_id character varying(50) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    CONSTRAINT "CUSTOMER_pkey" PRIMARY KEY (id),
    CONSTRAINT "CUSTOMER_customer_code_key" UNIQUE (customer_code)
);

CREATE TABLE IF NOT EXISTS public."FILE"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    original_file_name character varying(300) COLLATE pg_catalog."default" NOT NULL,
    new_file_name character varying(300) COLLATE pg_catalog."default",
    file_size integer,
    container_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    storage_type character varying(200) COLLATE pg_catalog."default",
    output_file_name character varying(300) COLLATE pg_catalog."default",
    file_path character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT "FILE_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."INPUT_FILE"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    shipment character varying(100) COLLATE pg_catalog."default",
    customer character varying(100) COLLATE pg_catalog."default",
    supplier character varying(100) COLLATE pg_catalog."default",
    volume double precision,
    quantity double precision,
    pol character varying(100) COLLATE pg_catalog."default",
    pod character varying(100) COLLATE pg_catalog."default",
    date timestamp with time zone,
    file_id bigint,
    bucket character varying(100) COLLATE pg_catalog."default",
    container character varying(100) COLLATE pg_catalog."default",
    priority_index character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "INPUT_FILE_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."MASTER_PRIVILEGE"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PRIVILEGE_NAME" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "PRIVILEGE_DESC" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    "MODULE_ID" character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "MASTER_PRIVILEGE_pkey" PRIMARY KEY (id),
    CONSTRAINT "MASTER_PRIVILEGE_PRIVILEGE_NAME_key" UNIQUE ("PRIVILEGE_NAME")
);

CREATE TABLE IF NOT EXISTS public."OUTPUT_FILE"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    container_ref character varying(250) COLLATE pg_catalog."default" NOT NULL,
    container_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    shipment character varying(100) COLLATE pg_catalog."default",
    customer character varying(100) COLLATE pg_catalog."default",
    supplier character varying(100) COLLATE pg_catalog."default",
    cbm double precision,
    total_cbm double precision,
    qty double precision,
    total_qty double precision,
    pol character varying(100) COLLATE pg_catalog."default",
    pod character varying(100) COLLATE pg_catalog."default",
    min_threshold integer,
    max_threshold integer,
    file_id bigint,
    CONSTRAINT "OUTPUT_FILE_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PORT_OF_DESTINATION"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    country character varying(20) COLLATE pg_catalog."default" NOT NULL,
    city character varying(20) COLLATE pg_catalog."default",
    timezone character varying(50) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    CONSTRAINT "PORT_OF_DESTINATION_pkey" PRIMARY KEY (id),
    CONSTRAINT "PORT_OF_DESTINATION_code_key" UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public."PORT_OF_LOADING"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    country character varying(20) COLLATE pg_catalog."default" NOT NULL,
    city character varying(20) COLLATE pg_catalog."default",
    timezone character varying(50) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    CONSTRAINT "PORT_OF_LOADING_pkey" PRIMARY KEY (id),
    CONSTRAINT "PORT_OF_LOADING_code_key" UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public."ROLE"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    "ROLE_NAME" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "ROLE_DESC" character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT "ROLE_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ROLE_PRIVILEGE"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    "PRIVILEGE_ID" bigint NOT NULL,
    "ROLE_ID" bigint NOT NULL,
    CONSTRAINT "ROLE_PRIVILEGE_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TOKEN_MANAGEMENT"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    expiry_days integer NOT NULL,
    expiry_time timestamp with time zone,
    "TOKEN_TYPE" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    primary_token character varying(120) COLLATE pg_catalog."default",
    secondary_token character varying(120) COLLATE pg_catalog."default",
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    user_id bigint,
    CONSTRAINT "TOKEN_MANAGEMENT_pkey" PRIMARY KEY (id),
    CONSTRAINT "TOKEN_MANAGEMENT_user_id_key" UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public."USER_ROLE"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    "ROLE_ID" bigint NOT NULL,
    "USER_ID" bigint NOT NULL,
    CONSTRAINT "USER_ROLE_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_superuser boolean NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(15) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(15) COLLATE pg_catalog."default",
    organisation_name character varying(15) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    timezone character varying(50) COLLATE pg_catalog."default",
    country character varying(50) COLLATE pg_catalog."default",
    country_code character varying(4) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    last_login timestamp with time zone,
    is_application boolean NOT NULL,
    announcement_read_flag integer NOT NULL,
    created_on timestamp with time zone NOT NULL,
    created_by integer,
    modified_on timestamp with time zone,
    modified_by integer,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public."CONTAINER_PRIORITY"
    ADD CONSTRAINT "CONTAINER_PRIORITY_container_type_id_5cdb1b6d_fk_CONTAINER" FOREIGN KEY (container_type_id)
    REFERENCES public."CONTAINER_THRESHOLD" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "CONTAINER_PRIORITY_container_type_id_5cdb1b6d"
    ON public."CONTAINER_PRIORITY"(container_type_id);


ALTER TABLE IF EXISTS public."CONTAINER_THRESHOLD"
    ADD CONSTRAINT "CONTAINER_THRESHOLD_container_id_589c262e_fk_CONTAINER_id" FOREIGN KEY (container_id)
    REFERENCES public."CONTAINER" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "CONTAINER_THRESHOLD_container_id_589c262e"
    ON public."CONTAINER_THRESHOLD"(container_id);


ALTER TABLE IF EXISTS public."CONTAINER_THRESHOLD"
    ADD CONSTRAINT "CONTAINER_THRESHOLD_port_of_loading_id_05aba615_fk_PORT_OF_L" FOREIGN KEY (port_of_loading_id)
    REFERENCES public."PORT_OF_LOADING" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "CONTAINER_THRESHOLD_port_of_loading_id_05aba615"
    ON public."CONTAINER_THRESHOLD"(port_of_loading_id);


ALTER TABLE IF EXISTS public."INPUT_FILE"
    ADD CONSTRAINT "INPUT_FILE_file_id_beb44235_fk_FILE_id" FOREIGN KEY (file_id)
    REFERENCES public."FILE" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "INPUT_FILE_file_id_beb44235"
    ON public."INPUT_FILE"(file_id);


ALTER TABLE IF EXISTS public."OUTPUT_FILE"
    ADD CONSTRAINT "OUTPUT_FILE_file_id_1005f1b2_fk_FILE_id" FOREIGN KEY (file_id)
    REFERENCES public."FILE" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "OUTPUT_FILE_file_id_1005f1b2"
    ON public."OUTPUT_FILE"(file_id);


ALTER TABLE IF EXISTS public."ROLE_PRIVILEGE"
    ADD CONSTRAINT "ROLE_PRIVILEGE_PRIVILEGE_ID_133016f4_fk_MASTER_PRIVILEGE_id" FOREIGN KEY ("PRIVILEGE_ID")
    REFERENCES public."MASTER_PRIVILEGE" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "ROLE_PRIVILEGE_PRIVILEGE_ID_133016f4"
    ON public."ROLE_PRIVILEGE"("PRIVILEGE_ID");


ALTER TABLE IF EXISTS public."ROLE_PRIVILEGE"
    ADD CONSTRAINT "ROLE_PRIVILEGE_ROLE_ID_c01787ef_fk_ROLE_id" FOREIGN KEY ("ROLE_ID")
    REFERENCES public."ROLE" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "ROLE_PRIVILEGE_ROLE_ID_c01787ef"
    ON public."ROLE_PRIVILEGE"("ROLE_ID");


ALTER TABLE IF EXISTS public."TOKEN_MANAGEMENT"
    ADD CONSTRAINT "TOKEN_MANAGEMENT_user_id_bbc62c03_fk_user_id" FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TOKEN_MANAGEMENT_user_id_key"
    ON public."TOKEN_MANAGEMENT"(user_id);


ALTER TABLE IF EXISTS public."USER_ROLE"
    ADD CONSTRAINT "USER_ROLE_ROLE_ID_e7b83f37_fk_ROLE_id" FOREIGN KEY ("ROLE_ID")
    REFERENCES public."ROLE" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "USER_ROLE_ROLE_ID_e7b83f37"
    ON public."USER_ROLE"("ROLE_ID");


ALTER TABLE IF EXISTS public."USER_ROLE"
    ADD CONSTRAINT "USER_ROLE_USER_ID_0d0a7fb0_fk_user_id" FOREIGN KEY ("USER_ID")
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "USER_ROLE_USER_ID_0d0a7fb0"
    ON public."USER_ROLE"("USER_ID");


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);

END;